#!/usr/bin/env python3
"""
Script para popular o banco de dados com a lista completa de equipamentos.
Execute após rodar a migration: alembic upgrade head
"""
import json
import sys
from datetime import datetime
from urllib import request
from urllib.error import HTTPError

API_BASE = "http://localhost:9000/api/v1/inventory/equipment"


def parse_brl_to_cents(value_str: str) -> int:
    """Converte string 'R$ 1.234,56' para centavos (123456)."""
    cleaned = value_str.replace("R$", "").replace(".", "").replace(",", ".").strip()
    return round(float(cleaned) * 100)


EQUIPMENT_DATA = [
    {
        "code": "001",
        "name": "Softbox Lanterna Bowens Greika 65 cm",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Caixa de luz difusa para iluminação profissional em estúdio",
        "unit_value_cents": parse_brl_to_cents("R$ 380,00"),
    },
    {
        "code": "002",
        "name": "Estante 6 Prateleiras de Aço na cor Preta",
        "category": "Mobiliário",
        "quantity": 2,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Armazenamento organizado para materiais diversos",
        "unit_value_cents": parse_brl_to_cents("R$ 250,00"),
    },
    {
        "code": "003",
        "name": "Mesa de Computador Industrial na cor Madeira",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Mobiliário robusto para trabalho com equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 200,00"),
    },
    {
        "code": "004",
        "name": "Mesa Dobrável de Alumínio com Tampo de MDF 90 x 60 CM",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Mesa portátil para montagens temporárias",
        "unit_value_cents": parse_brl_to_cents("R$ 162,00"),
    },
    {
        "code": "005",
        "name": "Microfone Fifine XLR AM8 Dinâmico Cardioide cor Preto",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Captação vocal profissional para estúdio",
        "unit_value_cents": parse_brl_to_cents("R$ 320,00"),
    },
    {
        "code": "006",
        "name": "Interface de Áudio Focusrite 3ª Gen Scarlett 2i2 3ª Geração",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Conversão de áudio analógico para digital",
        "unit_value_cents": parse_brl_to_cents("R$ 1900,00"),
    },
    {
        "code": "007",
        "name": "Iluminação Led Amaran 200xS Bicolor Cob Luz Contínua 200w",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Luz contínua profissional para vídeo e fotografia",
        "unit_value_cents": parse_brl_to_cents("R$ 2800,00"),
    },
    {
        "code": "008",
        "name": "Bastão Para Selfie Com Mini Controle Remoto Inova Sel-8548",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Acessório para captação de vídeos e fotos",
        "unit_value_cents": parse_brl_to_cents("R$ 40,00"),
    },
    {
        "code": "009",
        "name": "Máquina de Cartão de crédito",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Processamento de pagamentos por cartão",
        "unit_value_cents": parse_brl_to_cents("R$ 200,00"),
    },
    {
        "code": "010",
        "name": "Fone Headset Gamer Havit Hv-h2002d 3.5mm Cor Preto",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal/Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Áudio para jogos e comunicação",
        "unit_value_cents": parse_brl_to_cents("R$ 235,00"),
    },
    {
        "code": "011",
        "name": "Chroma Key verde Oxford e lycra 4 metros de largura e 3 de altura",
        "category": "Equipamento",
        "quantity": 3,
        "location": "Depósito/Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Fundo para efeitos de chroma key em vídeos",
        "unit_value_cents": parse_brl_to_cents("R$ 90,00"),
    },
    {
        "code": "012",
        "name": "Grampo de Prender o Chroma key",
        "category": "Equipamento",
        "quantity": 16,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Fixação para fundos e telas",
        "unit_value_cents": parse_brl_to_cents("R$ 3,13"),
    },
    {
        "code": "013",
        "name": "WAP Aspirador de Pó e Água GTW 10",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Limpeza de ambientes e equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 270,00"),
    },
    {
        "code": "014",
        "name": "Tripé de Ação Compacto Manfrotto MKCOMPACTACN-BK 60",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Suporte estável para câmeras e equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 1500,00"),
    },
    {
        "code": "015",
        "name": "Suporte Tripé de Chão P/ Caixa De Som Pedestal",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Base para sistema de som",
        "unit_value_cents": parse_brl_to_cents("R$ 150,00"),
    },
    {
        "code": "016",
        "name": "Tripé para Tela Mapa 2,80 Metros",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Suporte para telas e projetores",
        "unit_value_cents": parse_brl_to_cents("R$ 140,00"),
    },
    {
        "code": "017",
        "name": "Tripé de Iluminação Altura Máxima de 2 Metros",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Suporte para equipamentos de iluminação",
        "unit_value_cents": parse_brl_to_cents("R$ 80,00"),
    },
    {
        "code": "018",
        "name": "Suporte de Parede T Holder T120 P/ Estúdio E Iluminação 12cm",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Fixação em parede para equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 100,00"),
    },
    {
        "code": "019",
        "name": "Ferro de Passar Black + Decker Roupa a Seco",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Manutenção de roupas e figurinos",
        "unit_value_cents": parse_brl_to_cents("R$ 140,00"),
    },
    {
        "code": "020",
        "name": "Escada Multiuso de Alumínio 5 Degraus",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Acesso a pontos altos e manutenção",
        "unit_value_cents": parse_brl_to_cents("R$ 180,00"),
    },
    {
        "code": "021",
        "name": "Mochila Pirulito Acessibilidade",
        "category": "Equipamento",
        "quantity": 4,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Armazenamento para equipamentos de acessibilidade",
        "unit_value_cents": parse_brl_to_cents("R$ 150,00"),
    },
    {
        "code": "022",
        "name": "Rádio de Audiodescrição",
        "category": "Equipamento",
        "quantity": 20,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Transmissão de audiodescrição para deficientes visuais",
        "unit_value_cents": parse_brl_to_cents("R$ 110,00"),
    },
    {
        "code": "023",
        "name": "Fone de ouvido para shows kz-EDX PRO",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Monitoramento de áudio em apresentações",
        "unit_value_cents": parse_brl_to_cents("R$ 150,00"),
    },
    {
        "code": "024",
        "name": "Teclado e Mouse com fio USB",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Periféricos para computador",
        "unit_value_cents": parse_brl_to_cents("R$ 70,00"),
    },
    {
        "code": "025",
        "name": "Carregador Portátil 20000 mah 50w Power Bank",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Energia móvel para dispositivos eletrônicos",
        "unit_value_cents": parse_brl_to_cents("R$ 220,00"),
    },
    {
        "code": "026",
        "name": "Microfone para Palestra Com Fio De 3m Alta Frequência",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-01-01",
        "notes": "Captação vocal para apresentações",
        "unit_value_cents": parse_brl_to_cents("R$ 40,00"),
    },
    {
        "code": "027",
        "name": "Transmissor sem fio para Audiodescrição",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Transmissão wireless de audiodescrição",
        "unit_value_cents": parse_brl_to_cents("R$ 250,00"),
    },
    {
        "code": "028",
        "name": "Frigobar Philco 92 Litros Inox PFG111I 110V",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Refrigeração para alimentos e bebidas",
        "unit_value_cents": parse_brl_to_cents("R$ 1189,07"),
    },
    {
        "code": "029",
        "name": "Purificador Electrolux Eletrônico Compacto Experience Pure 4x Digital Cinza (PE12G)",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Filtragem e fornecimento de água potável",
        "unit_value_cents": parse_brl_to_cents("R$ 699,00"),
    },
    {
        "code": "030",
        "name": "Micro-ondas Electrolux 23L Prata",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Aquecimento rápido de alimentos",
        "unit_value_cents": parse_brl_to_cents("R$ 670,00"),
    },
    {
        "code": "031",
        "name": "Cafeteira Elétrica Electrolux 15 Xícaras",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Preparo de café para equipe",
        "unit_value_cents": parse_brl_to_cents("R$ 150,00"),
    },
    {
        "code": "032",
        "name": "Mesa De Jantar industrial 6 Pessoas",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Mobiliário para refeições em grupo",
        "unit_value_cents": parse_brl_to_cents("R$ 420,00"),
    },
    {
        "code": "033",
        "name": "Banquetas Argila Alta para Balcão Gourmet",
        "category": "Mobiliário",
        "quantity": 5,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Assentos para área de alimentação",
        "unit_value_cents": parse_brl_to_cents("R$ 134,00"),
    },
    {
        "code": "034",
        "name": "Notebook Gamer Acer Nitro 5 Intel Core i7-11800H, GeForce GTX 1650, 8GB RAM, SSD 512GB, 15.6 Full HD 144Hz IPS, Windows 11, Preto",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Computação de alto desempenho para edição e jogos",
        "unit_value_cents": parse_brl_to_cents("R$ 5270,00"),
    },
    {
        "code": "035",
        "name": "Tablet Samsung Galaxy Tab S6 Lite com Caneta 10,4\" 64GB 4GB RAM",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Casa Gabriel",
        "acquisition_date": "2025-01-01",
        "notes": "Dispositivo móvel para apresentações e anotações",
        "unit_value_cents": parse_brl_to_cents("R$ 1800,00"),
    },
    {
        "code": "036",
        "name": "Armário Roupeiro Aço 8 Portas",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Cozinha",
        "acquisition_date": "2025-01-01",
        "notes": "Armazenamento para materiais diversos",
        "unit_value_cents": parse_brl_to_cents("R$ 675,00"),
    },
    {
        "code": "037",
        "name": "Balcão para Escritório 3 portas na cor Branca",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Mobiliário organizacional para escritório",
        "unit_value_cents": parse_brl_to_cents("R$ 436,00"),
    },
    {
        "code": "038",
        "name": "Escrivaninha Studio na cor Branco e Pé Preto",
        "category": "Mobiliário",
        "quantity": 2,
        "location": "Sala Principal/Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Mesa de trabalho para computadores",
        "unit_value_cents": parse_brl_to_cents("R$ 366,00"),
    },
    {
        "code": "039",
        "name": "Cafeteira elétrica Arno Nescafe Dolce Gusto",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Preparo de cápsulas de café",
        "unit_value_cents": parse_brl_to_cents("R$ 600,00"),
    },
    {
        "code": "040",
        "name": "Extensão Tripolar com Carretel 20 Metros",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Distribuição de energia elétrica",
        "unit_value_cents": parse_brl_to_cents("R$ 188,00"),
    },
    {
        "code": "041",
        "name": "Carrinho de Café",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Serviço móvel de bebidas",
        "unit_value_cents": parse_brl_to_cents("R$ 350,00"),
    },
    {
        "code": "042",
        "name": "Monitor Gamer Samsung 27\" 75hz 5ms T350 Full Hd LF27T350FHLMZD",
        "category": "Equipamento",
        "quantity": 6,
        "location": "4 Sala Principal/ 2 Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Visualização de alta qualidade para trabalho e entretenimento",
        "unit_value_cents": parse_brl_to_cents("R$ 950,00"),
    },
    {
        "code": "043",
        "name": "Computador Simples",
        "category": "Equipamento",
        "quantity": 3,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Estação de trabalho básica",
        "unit_value_cents": parse_brl_to_cents("R$ 3000,00"),
    },
    {
        "code": "044",
        "name": "Computador de Edição",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Estação avançada para edição de vídeo",
        "unit_value_cents": parse_brl_to_cents("R$ 15000,00"),
    },
    {
        "code": "045",
        "name": "Kit Teclado Sem Fio Dell",
        "category": "Equipamento",
        "quantity": 5,
        "location": "Sala Principal/Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Periféricos wireless para computadores",
        "unit_value_cents": parse_brl_to_cents("R$ 230,00"),
    },
    {
        "code": "046",
        "name": "Ar Condicionado Split Hi Wall Electrolux Color Adapt 24000 BTU/h Frio 3124IFBA206 220 Volts",
        "category": "Eletrodoméstico",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Climatização de ambiente",
        "unit_value_cents": parse_brl_to_cents("R$ 5000,00"),
    },
    {
        "code": "047",
        "name": "Estação de Trabalho na cor Branca",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Mobiliário especializado para trabalho",
        "unit_value_cents": parse_brl_to_cents("R$ 1000,00"),
    },
    {
        "code": "048",
        "name": "Smart Tv 4k 65 Lg Uhd 65ut8050 Processador A5 Ger7 Ai Alexa",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Gs Cursos",
        "acquisition_date": "2025-01-01",
        "notes": "Exibição de conteúdo em alta definição",
        "unit_value_cents": parse_brl_to_cents("R$ 2800,00"),
    },
    {
        "code": "049",
        "name": "Softbox Triopod 90 cm parabólico gkp-90",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Iluminação difusa profissional para estúdio",
        "unit_value_cents": parse_brl_to_cents("R$ 654,00"),
    },
    {
        "code": "050",
        "name": "Refletores Lâmpadas Led Luz Fria Mako t-8 Bivolt 6500k 60w",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Iluminação direta para sets de filmagem",
        "unit_value_cents": parse_brl_to_cents("R$ 1550,00"),
    },
    {
        "code": "051",
        "name": "Suporte para Tv de Chão",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Base para televisores",
        "unit_value_cents": parse_brl_to_cents("R$ 518,00"),
    },
    {
        "code": "052",
        "name": "Cadeira Universitária de Plástica na cor Azul",
        "category": "Mobiliário",
        "quantity": 30,
        "location": "Gs Cursos",
        "acquisition_date": "2025-01-01",
        "notes": "Assento para ambientes educacionais",
        "unit_value_cents": parse_brl_to_cents("R$ 177,00"),
    },
    {
        "code": "053",
        "name": "Cadeira de Escritório Dot Sky Blue",
        "category": "Mobiliário",
        "quantity": 5,
        "location": "4 Sala Principal/ 1 Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Assento ergonômico para trabalho",
        "unit_value_cents": parse_brl_to_cents("R$ 700,00"),
    },
    {
        "code": "054",
        "name": "Caixa De Som Partybox Encore Com Microfone Jbl Preta",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Sistema de áudio para eventos e apresentações",
        "unit_value_cents": parse_brl_to_cents("R$ 2900,00"),
    },
    {
        "code": "055",
        "name": "Micro Converter Bi Direcional para Show",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Conversão de sinal para apresentações",
        "unit_value_cents": parse_brl_to_cents("R$ 850,00"),
    },
    {
        "code": "056",
        "name": "Ar Condicionado Split Hi Wall",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Climatização ambiental",
        "unit_value_cents": parse_brl_to_cents("R$ 3600,00"),
    },
    {
        "code": "057",
        "name": "Fone de Ouvido Sem Fio, PHILIPSTWS, TAT1109BK/00, Bluetooth, Com Microfone",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-01-01",
        "notes": "Áudio wireless para comunicação",
        "unit_value_cents": parse_brl_to_cents("R$ 140,00"),
    },
    {
        "code": "058",
        "name": "Câmera Blackmagic Design Pocket Cinema 4k",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Captação profissional de vídeo cinematográfico",
        "unit_value_cents": parse_brl_to_cents("R$ 15000,00"),
    },
    {
        "code": "059",
        "name": "Tripé de Câmera Profissional",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-01-01",
        "notes": "Suporte estável para câmeras profissionais",
        "unit_value_cents": parse_brl_to_cents("R$ 1230,00"),
    },
    {
        "code": "060",
        "name": "Suporte para Tv de Parede",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Gs Cursos",
        "acquisition_date": "2025-09-29",
        "notes": "Fixação em parede para televisores",
        "unit_value_cents": parse_brl_to_cents("R$ 77,00"),
    },
    {
        "code": "061",
        "name": "Puff Redonda Pé Palito Suede",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-09-29",
        "notes": "Assento decorativo para ambiente",
        "unit_value_cents": parse_brl_to_cents("R$ 77,00"),
    },
    {
        "code": "062",
        "name": "Bolsa para Tripés de Iluminação Estudio 110 cm",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-10-01",
        "notes": "Transporte e proteção para equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 208,00"),
    },
    {
        "code": "063",
        "name": "Furadeira Parafusadeira Bateria 12v",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-10-01",
        "notes": "Ferramenta para montagens e manutenções",
        "unit_value_cents": parse_brl_to_cents("R$ 520,00"),
    },
    {
        "code": "064",
        "name": "Tomada Inteligente da Positivo",
        "category": "Equipamento",
        "quantity": 5,
        "location": "Estúdio",
        "acquisition_date": "2025-10-01",
        "notes": "Controle remoto de dispositivos elétricos",
        "unit_value_cents": parse_brl_to_cents("R$ 72,00"),
    },
    {
        "code": "065",
        "name": "Iluminação Amaran 150c",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-06",
        "notes": "Luz contínua LED para produção visual",
        "unit_value_cents": parse_brl_to_cents("R$ 2100,00"),
    },
    {
        "code": "066",
        "name": "Gaveteiro Organizador 3 Gavetas",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Estúdio",
        "acquisition_date": "2025-10-06",
        "notes": "Armazenamento organizado para materiais",
        "unit_value_cents": parse_brl_to_cents("R$ 240,00"),
    },
    {
        "code": "067",
        "name": "Softbox Grid 60cm Octa Bowens Dobravel",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-06",
        "notes": "Controle de iluminação com grid",
        "unit_value_cents": parse_brl_to_cents("R$ 535,00"),
    },
    {
        "code": "068",
        "name": "Tripé De Iluminação Greika",
        "category": "Equipamento",
        "quantity": 2,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-06",
        "notes": "Suporte para equipamentos de luz",
        "unit_value_cents": parse_brl_to_cents("R$ 250,00"),
    },
    {
        "code": "069",
        "name": "Três Tabelas Box",
        "category": "Mobiliário",
        "quantity": 2,
        "location": "Estúdio",
        "acquisition_date": "2025-10-06",
        "notes": "Mobiliário modular para organização",
        "unit_value_cents": parse_brl_to_cents("R$ 180,00"),
    },
    {
        "code": "070",
        "name": "Bolsa de Cabos",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-06",
        "notes": "Organização e transporte de cabos",
        "unit_value_cents": parse_brl_to_cents("R$ 342,00"),
    },
    {
        "code": "071",
        "name": "Case Baú Acessórios 100x50x50 Com Rodas",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-06",
        "notes": "Armazenamento móvel para equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 1800,00"),
    },
    {
        "code": "072",
        "name": "Carregador para o conversor da câmera Baseus",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-07",
        "notes": "Energia para equipamentos de câmera",
        "unit_value_cents": parse_brl_to_cents("R$ 90,00"),
    },
    {
        "code": "073",
        "name": "Mochila Profissional Câmera",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-10-08",
        "notes": "Transporte seguro para equipamentos fotográficos",
        "unit_value_cents": parse_brl_to_cents("R$ 395,00"),
    },
    {
        "code": "074",
        "name": "Bolsa de Couro para equipamentos",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2025-10-21",
        "notes": "Proteção e transporte de dispositivos",
        "unit_value_cents": parse_brl_to_cents("R$ 80,00"),
    },
    {
        "code": "075",
        "name": "Carrinho para carregar peso",
        "category": "Mobiliário",
        "quantity": 1,
        "location": "Depósito",
        "acquisition_date": "2025-10-21",
        "notes": "Transporte de cargas e equipamentos",
        "unit_value_cents": parse_brl_to_cents("R$ 180,00"),
    },
    {
        "code": "076",
        "name": "Webcam C920s Pro Full Hd Com Microfone Embutido Logitech Cor Preto",
        "category": "Equipamento",
        "quantity": 1,
        "location": "Sala Principal",
        "acquisition_date": "2023-10-22",
        "notes": "Captação de vídeo e áudio para reuniões",
        "unit_value_cents": parse_brl_to_cents("R$ 450,00"),
    },
]


def create_equipment(item: dict) -> None:
    """Cria um equipamento via API."""
    payload = {
        "code": item["code"],
        "name": item["name"],
        "category": item["category"],
        "acquisition_date": f"{item['acquisition_date']}T00:00:00Z",
        "status": "available",
        "location": item.get("location"),
        "notes": item.get("notes"),
        "quantity": item.get("quantity", 1),
        "unit_value_cents": item.get("unit_value_cents"),
    }

    req = request.Request(
        API_BASE,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with request.urlopen(req) as response:
            print(f"✓ {item['code']} - {item['name']}")
    except HTTPError as err:
        print(f"✗ {item['code']} - {item['name']} (HTTP {err.code})", file=sys.stderr)
        print(f"  {err.read().decode()}", file=sys.stderr)


def main() -> None:
    print(f"Inserindo {len(EQUIPMENT_DATA)} equipamentos...")
    for idx, item in enumerate(EQUIPMENT_DATA, start=1):
        print(f"[{idx}/{len(EQUIPMENT_DATA)}] ", end="")
        create_equipment(item)
    print("\n✓ Seed concluído!")


if __name__ == "__main__":
    main()
