"""
Revision ID: 25d3ced2f0c7
Revises: 
Create Date: 2025-10-30 16:51:45.322158
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25d3ced2f0c7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('optional_field', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo', sa.Enum('fisica', 'juridica', name='empresa_tipo'), nullable=False),
    sa.Column('cpf_cnpj', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('cep', sa.Text(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('complemento', sa.Text(), nullable=True),
    sa.Column('bairro', sa.Text(), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('contato_nome', sa.Text(), nullable=False),
    sa.Column('contato_email', sa.Text(), nullable=False),
    sa.Column('contato_telefone', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj', name='uq_clients_cpf_cnpj')
    )
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo', sa.Enum('fisica', 'juridica', name='empresa_tipo'), nullable=False),
    sa.Column('cpf_cnpj', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('razao_social', sa.Text(), nullable=True),
    sa.Column('nome_fantasia', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('contato_nome', sa.Text(), nullable=False),
    sa.Column('contato_email', sa.Text(), nullable=False),
    sa.Column('contato_telefone', sa.Text(), nullable=False),
    sa.Column('cep', sa.Text(), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('complemento', sa.Text(), nullable=True),
    sa.Column('bairro', sa.Text(), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj', name='uq_empresas_cpf_cnpj')
    )
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'in-use', 'maintenance', 'retired', name='equipment_status'), server_default=sa.text("'available'"), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_equipment_code')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_name', sa.Text(), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('category_other', sa.Text(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('transport_type', sa.Text(), nullable=True),
    sa.Column('transport_other', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WON', 'LOST', name='opportunity_status'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('probability', sa.Integer(), server_default=sa.text('50'), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('client_email', sa.Text(), nullable=True),
    sa.Column('responsible_user', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overtime_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_name', sa.Text(), nullable=False),
    sa.Column('overtime_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.Text(), nullable=False),
    sa.Column('end_time', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_modes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('installments', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('adjustment_rate', sa.Numeric(precision=8, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inclusion_mode', sa.Enum('manual', 'automatic', name='proposal_note_mode'), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_signatures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('signature_type', sa.Enum('govbr', 'custom', name='proposal_signature_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'revoked', name='proposal_signature_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('govbr_identifier', sa.Text(), nullable=True),
    sa.Column('govbr_last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.Column('signature_image_mime', sa.Text(), nullable=True),
    sa.Column('signature_image_width', sa.Integer(), nullable=True),
    sa.Column('signature_image_height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_secondary_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_equipment',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'equipment_id', name='pk_event_equipment')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('pn', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('from_status', sa.Enum('OPEN', 'IN_PROGRESS', 'WON', 'LOST', name='opportunity_status'), nullable=True),
    sa.Column('to_status', sa.Enum('OPEN', 'IN_PROGRESS', 'WON', 'LOST', name='opportunity_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'SENT', 'WON', 'LOST', name='proposal_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('client_email', sa.Text(), nullable=True),
    sa.Column('client_phone', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('payment_mode', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=True),
    sa.Column('responsible_user', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_proposals_code')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='activity_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='activity_priority'), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_items')
    op.drop_table('activities')
    op.drop_table('proposals')
    op.drop_table('opportunity_activities')
    op.drop_table('items')
    op.drop_table('event_equipment')
    op.drop_table('client_secondary_contacts')
    op.drop_table('proposal_signatures')
    op.drop_table('proposal_notes')
    op.drop_table('payment_modes')
    op.drop_table('overtime_requests')
    op.drop_table('opportunities')
    op.drop_table('expense_reports')
    op.drop_table('events')
    op.drop_table('equipment')
    op.drop_table('empresas')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
