"""
Revision ID: 69873882579e
Revises: b2be72025581
Create Date: 2026-02-05 13:40:53.045555
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69873882579e'
down_revision = 'b2be72025581'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
