export type CanonicalCategory = "Equipamento" | "Mobiliário" | "Eletrodoméstico";

export type CanonicalEquipment = {
	id: string;
	name: string;
	category: CanonicalCategory;
	quantity: number;
	location: string;
	description: string;
	unitValueCents: number;
};

const BRL = (value: number): number => Math.round(value * 100);

export const CANONICAL_EQUIPMENT: CanonicalEquipment[] = [
	{
		id: "001",
		name: "Softbox Lanterna Bowens Greika 65 cm",
		category: "Equipamento",
		quantity: 2,
		location: "Depósito",
		description: "Softbox tipo lanterna para luz suave e difusa em 360°.",
		unitValueCents: BRL(760),
	},
	{
		id: "005",
		name: "Microfone Fifine XLR AM8",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Microfone dinâmico cardioide para voz e podcast.",
		unitValueCents: BRL(320),
	},
	{
		id: "006",
		name: "Interface Focusrite Scarlett 2i2 3ª Gen",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Interface 2x2 com pré-amps profissionais.",
		unitValueCents: BRL(1900),
	},
	{
		id: "007",
		name: "Iluminação Led Amaran 200xS Bicolor 200w",
		category: "Equipamento",
		quantity: 2,
		location: "Estúdio",
		description: "Luz COB bicolor de alta potência para filmagem.",
		unitValueCents: BRL(5600),
	},
	{
		id: "008",
		name: "Bastão para Selfie Inova",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Bastão selfie com controle remoto embutido.",
		unitValueCents: BRL(40),
	},
	{
		id: "009",
		name: "Máquina de Cartão de Crédito",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Terminal para pagamentos presenciais.",
		unitValueCents: BRL(200),
	},
	{
		id: "010",
		name: "Headset Gamer Havit HV-H2002D",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal/Estúdio",
		description: "Headset over-ear para monitoramento e uso geral.",
		unitValueCents: BRL(470),
	},
	{
		id: "011",
		name: "Chroma Key Oxford/Lycra 4m x 3m",
		category: "Equipamento",
		quantity: 3,
		location: "Depósito/Estúdio",
		description: "Fundo verde para recorte chroma key.",
		unitValueCents: BRL(270),
	},
	{
		id: "012",
		name: "Grampos para prender Chroma Key",
		category: "Equipamento",
		quantity: 16,
		location: "Depósito",
		description: "Grampos reforçados para fixação de tecido.",
		unitValueCents: BRL(50),
	},
	{
		id: "013",
		name: "Aspirador WAP GTW10 (pó e água)",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Aspirador compacto para limpeza profissional.",
		unitValueCents: BRL(270),
	},
	{
		id: "014",
		name: "Tripé Manfrotto MKCOMPACTACN-BK 60",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Tripé robusto para fotografia/vídeo.",
		unitValueCents: BRL(1500),
	},
	{
		id: "015",
		name: "Tripé para Caixa de Som",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Suporte pedestal para caixas de som.",
		unitValueCents: BRL(150),
	},
	{
		id: "016",
		name: "Tripé para Tela Mapa 2,80m",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Suporte para projeção/telas.",
		unitValueCents: BRL(140),
	},
	{
		id: "017",
		name: "Tripé de Iluminação 2m",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Suporte universal para iluminação.",
		unitValueCents: BRL(80),
	},
	{
		id: "018",
		name: "Suporte de Parede T Holder T120",
		category: "Equipamento",
		quantity: 2,
		location: "Depósito",
		description: "Suporte de parede para barras/iluminação.",
		unitValueCents: BRL(200),
	},
	{
		id: "019",
		name: "Ferro de Passar Black+Decker",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Ferro seco para figurino e fundos.",
		unitValueCents: BRL(140),
	},
	{
		id: "021",
		name: "Mochila Pirulito Acessibilidade",
		category: "Equipamento",
		quantity: 4,
		location: "Depósito",
		description: "Kit de acessibilidade para eventos.",
		unitValueCents: BRL(600),
	},
	{
		id: "022",
		name: "Rádio de Audiodescrição",
		category: "Equipamento",
		quantity: 20,
		location: "Sala Principal",
		description: "Receptores usados em acessibilidade AD.",
		unitValueCents: BRL(2200),
	},
	{
		id: "023",
		name: "Fone KZ-EDX PRO",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal",
		description: "In-ear profissional para monitoria.",
		unitValueCents: BRL(300),
	},
	{
		id: "024",
		name: "Teclado e Mouse USB",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Periféricos básicos para operação.",
		unitValueCents: BRL(70),
	},
	{
		id: "025",
		name: "Power Bank 20.000mAh 50W",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Carregador portátil de alta capacidade.",
		unitValueCents: BRL(220),
	},
	{
		id: "026",
		name: "Microfone para Palestra (com fio)",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Microfone com fio para eventos.",
		unitValueCents: BRL(40),
	},
	{
		id: "027",
		name: "Transmissor sem fio p/ Audiodescrição",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal",
		description: "Emissor para sistemas de AD.",
		unitValueCents: BRL(500),
	},
	{
		id: "034",
		name: "Notebook Acer Nitro 5",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Notebook gamer para edição e operação.",
		unitValueCents: BRL(5270),
	},
	{
		id: "035",
		name: "Tablet Samsung Tab S6 Lite",
		category: "Equipamento",
		quantity: 1,
		location: "Casa Gabriel",
		description: "Tablet com caneta para controle e anotações.",
		unitValueCents: BRL(1800),
	},
	{
		id: "039",
		name: "Cafeteira Arno Dolce Gusto",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Cafeteira compacta para suporte diário.",
		unitValueCents: BRL(600),
	},
	{
		id: "040",
		name: "Extensão Tripolar 20m",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Carretel de energia reforçado.",
		unitValueCents: BRL(188),
	},
	{
		id: "041",
		name: "Carrinho de Café",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Carrinho de apoio para gravações e cursos.",
		unitValueCents: BRL(350),
	},
	{
		id: "042",
		name: "Monitor Samsung 27\" 75Hz",
		category: "Equipamento",
		quantity: 6,
		location: "Sala/Estúdio",
		description: "Monitor FHD para edição e operação.",
		unitValueCents: BRL(5700),
	},
	{
		id: "043",
		name: "Computador Simples",
		category: "Equipamento",
		quantity: 3,
		location: "Sala Principal",
		description: "Estações básicas administrativas.",
		unitValueCents: BRL(9000),
	},
	{
		id: "044",
		name: "Computador de Edição",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Workstation profissional para pós.",
		unitValueCents: BRL(15000),
	},
	{
		id: "045",
		name: "Kit Teclado Sem Fio Dell",
		category: "Equipamento",
		quantity: 5,
		location: "Sala/Estúdio",
		description: "Periféricos wireless para mesas.",
		unitValueCents: BRL(1150),
	},
	{
		id: "048",
		name: "Smart TV 4k 65\" LG",
		category: "Equipamento",
		quantity: 1,
		location: "Gs Cursos",
		description: "TV para aulas e apresentações.",
		unitValueCents: BRL(2800),
	},
	{
		id: "049",
		name: "Softbox Triopod 90 cm (parabólico)",
		category: "Equipamento",
		quantity: 2,
		location: "Estúdio",
		description: "Softbox parabólico para luz suave e direcionada.",
		unitValueCents: BRL(1308),
	},
	{
		id: "050",
		name: "Refletores LED Mako T-8 60W",
		category: "Equipamento",
		quantity: 2,
		location: "Estúdio",
		description: "Iluminação fria de alta intensidade.",
		unitValueCents: BRL(3100),
	},
	{
		id: "051",
		name: "Suporte para TV de Chão",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Suporte móvel para TV/monitor.",
		unitValueCents: BRL(518),
	},
	{
		id: "054",
		name: "Caixa de Som JBL Partybox Encore",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Caixa de som potente com microfone.",
		unitValueCents: BRL(2900),
	},
	{
		id: "055",
		name: "Micro Converter Bi-Direcional",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Conversor SDI/HDMI profissional.",
		unitValueCents: BRL(850),
	},
	{
		id: "056",
		name: "Ar Condicionado Split Hi Wall",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Climatização para sala de trabalho.",
		unitValueCents: BRL(3600),
	},
	{
		id: "057",
		name: "Fone Philips TWS",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Fone bluetooth leve e portátil.",
		unitValueCents: BRL(140),
	},
	{
		id: "058",
		name: "Câmera Blackmagic Pocket Cinema 4K",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Câmera cinema 4K profissional.",
		unitValueCents: BRL(15000),
	},
	{
		id: "059",
		name: "Tripé de Câmera Profissional",
		category: "Equipamento",
		quantity: 1,
		location: "Estúdio",
		description: "Tripé estável com cabeça fluida.",
		unitValueCents: BRL(1230),
	},
	{
		id: "060",
		name: "Suporte para TV de Parede",
		category: "Equipamento",
		quantity: 1,
		location: "Gs Cursos",
		description: "Fixação de TV.",
		unitValueCents: BRL(77),
	},
	{
		id: "062",
		name: "Bolsa para Tripés 110 cm",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Bolsa para transporte de tripés.",
		unitValueCents: BRL(208),
	},
	{
		id: "063",
		name: "Furadeira/Parafusadeira 12v",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Ferramenta para montagem/instalação.",
		unitValueCents: BRL(520),
	},
	{
		id: "064",
		name: "Tomada Inteligente Positivo",
		category: "Equipamento",
		quantity: 5,
		location: "Estúdio",
		description: "Automação e controle de energia.",
		unitValueCents: BRL(360),
	},
	{
		id: "065",
		name: "Iluminação Amaran 150c",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal",
		description: "Luz COB RGBWW profissional.",
		unitValueCents: BRL(4200),
	},
	{
		id: "067",
		name: "Softbox Grid 60cm Octa Bowens",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal",
		description: "Softbox com grid para controle de spill.",
		unitValueCents: BRL(1070),
	},
	{
		id: "068",
		name: "Tripé de Iluminação Greika",
		category: "Equipamento",
		quantity: 2,
		location: "Sala Principal",
		description: "Suporte reforçado para iluminação.",
		unitValueCents: BRL(500),
	},
	{
		id: "070",
		name: "Bolsa de Cabos",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Organização e transporte de cabos.",
		unitValueCents: BRL(342),
	},
	{
		id: "071",
		name: "Case Baú Acessórios 100×50×50",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Baú rígido com rodas para transporte pesado.",
		unitValueCents: BRL(1800),
	},
	{
		id: "072",
		name: "Carregador Baseus p/ Conversor",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Fonte/carregador para conversor da câmera.",
		unitValueCents: BRL(90),
	},
	{
		id: "073",
		name: "Mochila Profissional p/ Câmera",
		category: "Equipamento",
		quantity: 1,
		location: "Depósito",
		description: "Mochila acolchoada para equipamentos.",
		unitValueCents: BRL(395),
	},
	{
		id: "074",
		name: "Bolsa de Couro p/ Equipamentos",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Bolsa reforçada para transporte geral.",
		unitValueCents: BRL(80),
	},
	{
		id: "076",
		name: "Webcam Logitech C920s Pro Full HD",
		category: "Equipamento",
		quantity: 1,
		location: "Sala Principal",
		description: "Webcam Full HD para transmissão e reunião.",
		unitValueCents: BRL(450),
	},
	{
		id: "002",
		name: "Estante 6 Prateleiras Aço Preta",
		category: "Mobiliário",
		quantity: 2,
		location: "Depósito",
		description: "Estante resistente para armazenagem pesada.",
		unitValueCents: BRL(500),
	},
	{
		id: "003",
		name: "Mesa de Computador Industrial",
		category: "Mobiliário",
		quantity: 1,
		location: "Depósito",
		description: "Mesa de apoio robusta com tampo madeira.",
		unitValueCents: BRL(200),
	},
	{
		id: "004",
		name: "Mesa Dobrável Alumínio 90x60",
		category: "Mobiliário",
		quantity: 1,
		location: "Depósito",
		description: "Mesa dobrável portátil para apoio.",
		unitValueCents: BRL(162),
	},
	{
		id: "020",
		name: "Escada Multiuso Alumínio 5 Degraus",
		category: "Mobiliário",
		quantity: 1,
		location: "Depósito",
		description: "Escada leve para montagem e manutenção.",
		unitValueCents: BRL(180),
	},
	{
		id: "032",
		name: "Mesa de Jantar Industrial 6 Pessoas",
		category: "Mobiliário",
		quantity: 1,
		location: "Cozinha",
		description: "Mesa grande para refeições e reuniões.",
		unitValueCents: BRL(420),
	},
	{
		id: "033",
		name: "Banquetas Argila Altas",
		category: "Mobiliário",
		quantity: 5,
		location: "Cozinha",
		description: "Banquetas para balcão e área gourmet.",
		unitValueCents: BRL(670),
	},
	{
		id: "036",
		name: "Armário Roupeiro Aço 8 Portas",
		category: "Mobiliário",
		quantity: 1,
		location: "Cozinha",
		description: "Armário para guardar materiais e pertences.",
		unitValueCents: BRL(675),
	},
	{
		id: "037",
		name: "Balcão Escritório 3 Portas Branca",
		category: "Mobiliário",
		quantity: 1,
		location: "Sala Principal",
		description: "Balcão de armazenamento e apoio administrativo.",
		unitValueCents: BRL(436),
	},
	{
		id: "038",
		name: "Escrivaninha Studio Branca/Pé Preto",
		category: "Mobiliário",
		quantity: 2,
		location: "Sala/Estúdio",
		description: "Mesas para trabalho e operação.",
		unitValueCents: BRL(732),
	},
	{
		id: "047",
		name: "Estação de Trabalho Branca",
		category: "Mobiliário",
		quantity: 1,
		location: "Sala Principal",
		description: "Mesa ampla para edição e produção.",
		unitValueCents: BRL(1000),
	},
	{
		id: "052",
		name: "Cadeiras Universitárias Azuis",
		category: "Mobiliário",
		quantity: 30,
		location: "Gs Cursos",
		description: "Cadeiras com prancheta para aulas/treinamentos.",
		unitValueCents: BRL(5310),
	},
	{
		id: "053",
		name: "Cadeiras Escritório Dot Sky Blue",
		category: "Mobiliário",
		quantity: 5,
		location: "Sala/Estúdio",
		description: "Cadeiras ergonômicas para uso prolongado.",
		unitValueCents: BRL(3500),
	},
	{
		id: "061",
		name: "Puff Redondo Pé Palito",
		category: "Mobiliário",
		quantity: 1,
		location: "Estúdio",
		description: "Puff de apoio decorativo.",
		unitValueCents: BRL(77),
	},
	{
		id: "066",
		name: "Gaveteiro Organizador 3 Gavetas",
		category: "Mobiliário",
		quantity: 1,
		location: "Estúdio",
		description: "Gaveteiro para documentos e acessórios.",
		unitValueCents: BRL(240),
	},
	{
		id: "069",
		name: "Tabelas Box (3 peças)",
		category: "Mobiliário",
		quantity: 2,
		location: "Estúdio",
		description: "Estruturas multiuso p/ apoio e cenografia.",
		unitValueCents: BRL(360),
	},
	{
		id: "075",
		name: "Carrinho para Carregar Peso",
		category: "Mobiliário",
		quantity: 1,
		location: "Depósito",
		description: "Carrinho para transporte de equipamentos pesados.",
		unitValueCents: BRL(180),
	},
	{
		id: "028",
		name: "Frigobar Philco 92L Inox",
		category: "Eletrodoméstico",
		quantity: 1,
		location: "Cozinha",
		description: "Mini geladeira para bebidas/alimentos.",
		unitValueCents: BRL(1189.07),
	},
	{
		id: "029",
		name: "Purificador Electrolux PE12G",
		category: "Eletrodoméstico",
		quantity: 1,
		location: "Cozinha",
		description: "Purificador digital de água.",
		unitValueCents: BRL(699),
	},
	{
		id: "030",
		name: "Micro-ondas Electrolux 23L",
		category: "Eletrodoméstico",
		quantity: 1,
		location: "Cozinha",
		description: "Aquecimento rápido para uso diário.",
		unitValueCents: BRL(670),
	},
	{
		id: "031",
		name: "Cafeteira Electrolux 15 xícaras",
		category: "Eletrodoméstico",
		quantity: 1,
		location: "Cozinha",
		description: "Cafeteira elétrica de grande volume.",
		unitValueCents: BRL(150),
	},
	{
		id: "046",
		name: "Ar Condicionado Electrolux Color Adapt 24.000 BTU",
		category: "Eletrodoméstico",
		quantity: 1,
		location: "Estúdio",
		description: "Climatização de alta capacidade.",
		unitValueCents: BRL(5000),
	},
];
